### ISSUE TITLE
RuntimeError: Don't know how to mount this partition

### ISSUE THREAD

**Issue by Realiserad** [dlenski/tetherback#56]
Hi, I ran into some issues when creating a backup. Can you advice?

```
> tetherback
tetherback v0.9.1
Found ADB version 1.0.32
Using default transfer method: adb exec-out pipe (--exec-out)
Device reports kernel 3.10.73-g2d9f644
Device reports TWRP version 3.0.2-0
Reading partition map for mmcblk0 (46 partitions)...
  partition map: 100%                                                          
Reading partition map for mmcblk0rpmb (0 partitions)...
  partition map: 100%                                                          
Saving backup images in ./twrp-backup-2017-11-05--20-40-58/ ...
Saving partition boot (mmcblk0p37), 32 MiB uncompressed...
  boot.emmc.win: 100%   5.2 MiB/s  12.1 MiB                                    
Saving tarball of mmcblk0p41 (mounted at /system), 3072 MiB uncompressed...
  system.ext4.win: 100%   6.2 MiB/s 772.9 MiB                                  
Traceback (most recent call last):
  File "/home/realiserad/.local/bin/tetherback", line 9, in <module>
    load_entry_point('tetherback==0.9.1', 'console_scripts', 'tetherback')()
  File "/home/realiserad/.local/lib/python3.5/site-packages/tetherback/tetherback.py", line 338, in main
    backup_partition(adb, partmap[standard], bp, args.transport, backupdir, args.verify)
  File "/home/realiserad/.local/lib/python3.5/site-packages/tetherback/tetherback.py", line 229, in backup_partition
    raise RuntimeError("%s: don't know how to mount this partition" % pi.devname)
RuntimeError: mmcblk0p45: don't know how to mount this partition
```

I have a Nexus 5X with TWRP 3.0.2-0. I use Ubuntu 16.04 with Android Debug Bridge version 1.0.32. The device is encrypted.

What have I done wrong and/or is this a bug in your script?

Cheers,
Bastian

**Comment by Realiserad** [comment]
Should be the same as #42 so I'll close this as a duplicate.
